systemInfo:
  appName: @project.artifactId@
server:
  port: 8082
logging:
  registry:
    files:
    - name: info
      description: 标准输出
      path: logs/${spring.application.name}/info.log
    - name: gclog
      path: logs/${spring.application.name}/gc.log


management.server.port: 8992